dir('jenkins/LAB-24/my-shared-library/vars')
@Library('my-shared-library') _

pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'docker.io/marwanhesham463/ivolve'
        KUBE_NAMESPACE = 'default'
        DEPLOYMENT_YAML = '/var/lib/jenkins/workspace/lab23/jenkins/LAB-23/jenkins/LAB-23/deployment.yaml'
    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    git url: 'https://github.com/IbrahimAdell/Lab.git', branch: 'main'
                    dir('jenkins/LAB-24/my-shared-library/vars') {
                        git url: 'https://github.com/Marwan933/ivolve_training.git', branch: 'main'
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerActions.buildAndPushDockerImage(DOCKER_IMAGE)
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    dockerActions.buildAndPushDockerImage(DOCKER_IMAGE)
                }
            }
        }

        stage('Edit Deployment.yaml') {
            steps {
                script {
                    def utils = new com.mycompany.JenkinsUtils(script)
                    utils.updateDeploymentImage(DEPLOYMENT_YAML, DOCKER_IMAGE)
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    deployToK8s("/var/lib/jenkins/.kube/config", DEPLOYMENT_YAML, KUBE_NAMESPACE)
                }
            }
        }

        stage('Post Action') {
            steps {
                script {
                    echo "Deployment to Kubernetes completed successfully!"
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline executed successfully...!"
        }
        failure {
            echo "Pipeline failed."
        }
    }
}
