
@Library('my-shared-library') _

pipeline {
    agent any
    environment {
        DOCKER_IMAGE = 'docker.io/marwanhesham463/ivolve'
        KUBE_NAMESPACE = 'default'
        DEPLOYMENT_YAML = 'deployment.yaml' 

    }
    stages {
        stage('Checkout') {
            steps {
                script {
                    
                    gitLib.checkoutRepository('https://github.com/IbrahimAdell/Lab.git', 'main')

                    dir('jenkins/LAB-24/my-shared-library/vars') {
                      
                        gitLib.checkoutRepository('https://github.com/Marwan933/ivolve_training.git', 'main')
                    }
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    dockerLib.buildImage(env.DOCKER_IMAGE)
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    dockerLib.pushImage(env.DOCKER_IMAGE, 'Docker_hub')
                }
            }
        }

      stage('Edit Deployment.yaml') {
    steps {
        script {
            
            sh 'ls -la jenkins/LAB-24/'
            
            sh 'sed -i "s|image:.*|image: docker.io/marwanhesham463/ivolve|g" jenkins/LAB-24/deployment.yaml'
        }
    }
}



        stage('Deploy to Kubernetes') {
            steps {
                script {
                    kubernetesLib.deployToKubernetes('/home/jenkins/.kube/config', env.K8S_TOKEN, env.DEPLOYMENT_YAML, env.KUBE_NAMESPACE)
                }
            }
        }

        stage('Post Action') {
            steps {
                script {
                    echo "Deployment to Kubernetes completed successfully!"
                }
            }
        }
    }

    post {
        success {
            echo "Pipeline executed successfully."
        }
        failure {
            echo "Pipeline failed."
        }
    }
}
