apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
  clusterIP: 10.96.14.15  # Headless service for StatefulSet
  selector:
    app: mysql

